# Form implementation generated from reading ui file 'circleCal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(70, 40, 55, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 55, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 120, 55, 18))
        self.label_3.setObjectName("label_3")
        self.leRadius = QtWidgets.QLineEdit(parent=Dialog)
        self.leRadius.setGeometry(QtCore.QRect(110, 40, 241, 25))
        self.leRadius.setObjectName("leRadius")
        self.leLength = QtWidgets.QLineEdit(parent=Dialog)
        self.leLength.setEnabled(False)
        self.leLength.setGeometry(QtCore.QRect(110, 80, 241, 25))
        self.leLength.setObjectName("leLength")
        self.leArea = QtWidgets.QLineEdit(parent=Dialog)
        self.leArea.setEnabled(False)
        self.leArea.setGeometry(QtCore.QRect(110, 120, 241, 25))
        self.leArea.setText("")
        self.leArea.setObjectName("leArea")
        self.pbCal = QtWidgets.QPushButton(parent=Dialog)
        self.pbCal.setGeometry(QtCore.QRect(140, 190, 111, 26))
        self.pbCal.setObjectName("pbCal")

        self.retranslateUi(Dialog)
        self.pbCal.clicked.connect(Dialog.calCircle) # type: ignore
        self.leRadius.returnPressed.connect(Dialog.calCircle) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "半径="))
        self.label_2.setText(_translate("Dialog", "周长="))
        self.label_3.setText(_translate("Dialog", "面积="))
        self.pbCal.setText(_translate("Dialog", "计算"))
